ci:
  autoupdate_schedule: monthly
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.6
  hooks:
    - id: ruff
    - id: ruff-format
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.38.0
  hooks:
    - id: check-github-workflows
    - id: check-readthedocs
