# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U . --use-mirrors

# command to run tests, e.g. python setup.py test
script: nosetests