language: python
dist: xenial
cache: pip
install: travis_retry pip install -U tox
script: tox
jobs:
  include:
  - { python: '3.7', env: TOXENV=lint }
  - { python: '3.6', env: TOXENV=py36 }
  - { python: '3.7', env: TOXENV=py37 }

  - stage: PyPI Release
    if: tag IS present
    python: "3.6"
    env: []
    install: skip
    script: skip
    deploy:
      provider: pypi
      user: sloria
      on:
        tags: true
      distributions: sdist bdist_wheel
      password:
        secure: "C3C2DxdjdZ37g9mSsyXY7WtyfinosmUsZCWutlei2jGsj9TWMVRVHBxbrHjSrhMoenxmmK3K1JsTLawvd1Pev8Zf7y8WOpPy79Q6QKaVLk0CtFKkzvNjzltldscLviAj03lVbmYi7dPbW9zOzx0jJTqJkvGJKgeqH5+aQponAoY="
