trigger:
  branches:
    include: [master]

resources:
  repositories:
    - repository: sloria
      type: github
      endpoint: github
      name: sloria/azure-pipeline-templates
      ref: refs/heads/sloria

jobs:
- template: job--python-tox.yml@sloria
  parameters:
    toxenvs: [lint, py36, py37]
    os: linux
- template: job--pypi-release.yml@sloria
  dependsOn:
    - tox_linux lint
    - tox_linux py36
    - tox_linux py37
